export { default as CommonCard } from './card.vue'
export { default as CommonArea } from './area.vue'
export { default as CommonButton } from './button.vue'
export { default as CommonRangePicker } from './rangePicker.vue'
export { default as CommonTabs } from './tab/tabs.vue'
export { default as CommonTabPane } from './tab/tabPane.vue'
