spring:
  application:
    name: satellite-user
  config:
    import:
      - nacos:satellite-user.yaml?refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: 223.2.43.228:30848
        namespace: 0fd34842-08ff-45f3-8a8c-8f3daf770d6f
        enabled: true
        group: PROD
#        group: DEV
      config:
        server-addr: 223.2.43.228:30848
        file-extension: yaml
        namespace: 0fd34842-08ff-45f3-8a8c-8f3daf770d6f
        group: PROD
#        group: DEV
#logging:
#  level:
#    com.alibaba.cloud.nacos.configdata.NacosConfigDataLoader: DEBUG