spring:
  application:
    name: satellite-opengmp
  config:
    import:
      - nacos:satellite-opengmp-dev.yaml?refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: 223.2.43.228:30848
        namespace: 0fd34842-08ff-45f3-8a8c-8f3daf770d6f
        enabled: true
      config:
        server-addr: 223.2.43.228:30848
        file-extension: yaml
        namespace: 0fd34842-08ff-45f3-8a8c-8f3daf770d6f