server:
  port: 8999

netty:
  websocket:
    port: 9000

spring:
  datasource:
    dynamic:
      primary: mysql_satellite
      strict: false
      datasource:
        mysql_satellite:
          url: jdbc:mysql://192.168.1.101:3306/satellite
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            connection-init-sql: SET SESSION group_concat_max_len = 18446744073709551615
        mysql_tile:
          url: jdbc:mysql://192.168.1.101:3306/tile
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        # PostgreSQL配置 - 请根据实际情况配置
        # pg_space:
        #   url: jdbc:postgresql://your-postgres-host:5432/gis_db
        #   username: postgres
        #   password: your-password
        #   driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  data:
    redis:
      host: 114.55.142.175
      port: 30379
      database: 0
    # MongoDB配置 - 请根据实际情况配置
    # mongodb:
    #   uri: mongodb://username:password@your-mongo-host:27017/database
  # Elasticsearch配置 - 请根据实际情况配置
  # elasticsearch:
  #   uris: http://your-es-host:9200

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: nnu.mnr.satellite.model.po
  type-handlers-package: nnu.mnr.satellite.utils.typeHandler
  # 开启SQL日志输出（调试时可以启用）
  # configuration:
  #   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  access-key: minioadmin
  secret-key: minioadmin
  url: http://192.168.1.101:30900
  # 备用地址: http://223.2.36.238:30901

# 简化Docker配置 - 全部使用本地路径
docker:
  defaultServer:
    port: 2375
    host: "223.2.35.153"
    username: "root"
    password: "dky.njnu.edu.cn"
  localPath: D:/satellite/modelDockerVolume/
  serverDir: /home/satellite/
  workDir: /usr/local/coding/

# 添加默认的模型服务器配置
modelServer:
  address: http://localhost:5002/
  apis:
    status: /v0/task/status
    result: /v0/task/result
    merge: /v0/tif/merge_v2
    spectrum: /v0/tif/get_spectral_profile
    noCloud: /v0/tif/calc_no_cloud
    rasterPoint: /v0/tif/calc_raster_point
    rasterLine: /v0/tif/calc_raster_line
    ndvi: /v0/tif/calc_NDVI
  interval:
    status: 2

# 瓦片服务配置 - 如果没有瓦片服务，请提供默认配置
tiler:
  end-point: http://192.168.1.101:8000

# 卫星配置文件路径 - 请根据实际情况配置
satelliteConfig:
  path: D:/satellite/band_config.json