server:
  port: 8999

netty:
  websocket:
    port: 9888

spring:
  datasource:
    dynamic:
      primary: mysql_satellite
      strict: false
      datasource:
        mysql_satellite:
          #          url: jdbc:mysql://223.2.34.7:3306/satellite
          url: jdbc:mysql://20.1.47.208:3306/satellite
          username: root
          #          password: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            connection-init-sql: SET SESSION group_concat_max_len = 18446744073709551615
        mysql_tile:
          #          url: jdbc:mysql://223.2.34.7:3306/tile
          url: jdbc:mysql://20.1.47.208:3306/tile
          username: root
          #          password: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        pg_space:
          url: jdbc:postgresql://20.1.19.121:5432/gis_db
          #          url: jdbc:postgresql://127.0.0.1:5431/gis_db
          username: postgres
          password: 123456
          #          password: ogms250410
          driver-class-name: org.postgresql.Driver
        pg_satellite:
          #          url: jdbc:postgresql://223.2.34.8:31543/satellite
          url: jdbc:postgresql://20.1.19.121:5432/satellite
          username: postgres
          password: 123456
          driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  data:
    redis:
      host: 20.1.184.29
      port: 6379
      database: 0
    mongodb:
      uri: mongodb://OGMSROOT:ogms1qaz2wsx@172.21.252.208:23266/opengmp
  elasticsearch:
    uris: http://20.1.51.153:9200
#    uris: http://127.0.0.1:9200

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: nnu.mnr.satellite.model.po
  type-handlers-package: nnu.mnr.satellite.utils.typeHandler
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#ca:
#  dir: /usr/resource/OpenSSL/ca

minio:
  access-key: jTbgNHEqQafOpUxVg7Ol
  secret-key: 7UxtrqhSOyN1KUeumbqTRMv1zeluLO69OwJnCC0M
  url: http://20.1.115.166:9000

docker:
  defaultServer:
    #    port: 2376
    #    host: "223.2.35.208"
    #    username: "vge"
    #    password: "3J44.njnu.edu.cn"
    #  serverDir: /home/vge/satellite/
    port: 2375
    host: "223.2.35.153"
    username: "root"
    password: "dky.njnu.edu.cn"
  localPath: /usr/resource/modelDockerVolume/
  serverDir: /home/satellite/
  workDir: /usr/local/coding/

modelServer:
  #  address: http://127.0.0.1:5001
  address: http://20.1.182.105:5000
  apis:
    status: /v0/task/status
    result: /v0/task/result
    merge: /v0/tif/merge_v2
    noCloud: /v0/tif/calc_no_cloud
    noCloud_complex: /v0/tif/calc_no_cloud_complex
    spectrum: /v0/tif/get_spectral_profile
    rasterPoint: /v0/tif/calc_raster_point
    rasterLine: /v0/tif/calc_raster_line
    #    noCloud: /v0/tif/calc_qa_simple
    #    noCloud: /v0/tif/calc_qa
    ndvi: /v0/tif/calc_NDVI
  interval:
    status: 2

tiler:
  end-point: http://20.1.37.145:8000

satelliteConfig:
  path: /usr/resource/band_config.json
