server:
  port: 8999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/satellite
#    url: jdbc:mysql://10.20.249.101:3306/satellite
    username: root
#    password: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: nnu.mnr.satellite.model.po
  type-handlers-package: nnu.mnr.satellite.util.typeHandler