server:
  port: 8999

netty:
  websocket:
    port: 9000

spring:
  datasource:
    dynamic:
      primary: mysql_satellite
      strict: false
      datasource:
        mysql_satellite:
          url: jdbc:mysql://223.2.34.7:3306/satellite
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        mysql_tile:
          url: jdbc:mysql://223.2.34.7:3306/tile
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
    mongodb:
      uri: mongodb://OGMSROOT:ogms1qaz2wsx@172.21.252.208:23266/opengmp

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: nnu.mnr.satellite.model.po
  type-handlers-package: nnu.mnr.satellite.utils.typeHandler
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ca:
  dir: /usr/resource/OpenSSL/ca

minio:
  access-key: jTbgNHEqQafOpUxVg7Ol
  secret-key: 7UxtrqhSOyN1KUeumbqTRMv1zeluLO69OwJnCC0M
  url: http://223.2.34.7:9000

docker:
  defaultServer:
    port: 2376
#    host: "127.0.0.1"
    host: "223.2.35.208"
    username: "vge"
    password: "3J44.njnu.edu.cn"
  localPath: /usr/resource/modelDockerVolume/
  serverDir: /home/vge/satellite/
  workDir: /usr/local/coding/

modelServer:
  address: http://223.2.34.7:5000
  apis:
    status: /v0/task/status
    result: /v0/task/result
    merge: /v0/tif/merge_v2
    ndviPoint: /ndviPoint
    ndviArea: /ndviArea
  interval:
    status: 2

tiler:
  end-point: http://223.2.32.242:8079