server:
  port: 8999

netty:
  websocket:
    port: 9888

mysql:
#  host: 20.1.47.208
#  port: 3306
  host: 223.2.34.8
  port: 31036
  username: root
  password: 123456
pg:
  host: 20.1.19.121
  port: 5432
  username: postgres
  password: 123456

# 修改数据库级相应配置注意兼顾在线编程写死部分
spring:
  datasource:
    dynamic:
      primary: mysql-ard-satellite
      strict: false
      datasource:
#        mysql_satellite:
#          url: jdbc:mysql://${mysql.host}:${mysql.port}/satellite
#          username: ${mysql.username}
#          password: ${mysql.password}
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          hikari:
#            connection-init-sql: SET SESSION group_concat_max_len = 18446744073709551615
        mysql-ard-satellite:
          url: jdbc:mysql://${mysql.host}:${mysql.port}/ard_satellite
          username: ${mysql.username}
          password: ${mysql.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            connection-init-sql: SET SESSION group_concat_max_len = 18446744073709551615
        mysql-ard-iam:
          url: jdbc:mysql://${mysql.host}:${mysql.port}/ard_iam
          username: ${mysql.username}
          password: ${mysql.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            connection-init-sql: SET SESSION group_concat_max_len = 18446744073709551615
        mysql-ard-dev:
          url: jdbc:mysql://${mysql.host}:${mysql.port}/ard_dev
          username: ${mysql.username}
          password: ${mysql.password}
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            connection-init-sql: SET SESSION group_concat_max_len = 18446744073709551615
#        mysql_tile:
#          url: jdbc:mysql://${mysql.host}:${mysql.port}/tile
#          username: ${mysql.username}
#          password: ${mysql.password}
#          driver-class-name: com.mysql.cj.jdbc.Driver
        pg_space:
          url: jdbc:postgresql://${pg.host}:${pg.port}/gis_db
          username: ${pg.username}
          password: ${pg.password}
          driver-class-name: org.postgresql.Driver
        pg-satellite:
          url: jdbc:postgresql://${pg.host}:${pg.port}/satellite
          username: ${pg.username}
          password: ${pg.password}
          driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  data:
    redis:
      host: 20.1.184.29
      port: 6379
      database: 0
    mongodb:
      uri: mongodb://OGMSROOT:ogms1qaz2wsx@172.21.252.208:23266/opengmp
  elasticsearch:
    uris: http://20.1.51.153:9200
#    uris: http://127.0.0.1:9200

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: nnu.mnr.satellite.model.po
  type-handlers-package: nnu.mnr.satellite.utils.typeHandler
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#ca:
#  dir: /usr/resource/OpenSSL/ca

minio:
  access-key: jTbgNHEqQafOpUxVg7Ol
  secret-key: 7UxtrqhSOyN1KUeumbqTRMv1zeluLO69OwJnCC0M
#  url: http://20.1.115.166:9000
  url: http://223.2.34.8:30900
docker:
  defaultServer:
    #    port: 2376
    #    host: "223.2.35.208"
    #    username: "vge"
    #    password: "3J44.njnu.edu.cn"
    #  serverDir: /home/vge/satellite/
    port: 2375
    host: "223.2.35.153"
    username: "root"
    password: "dky.njnu.edu.cn"
  localPath: /usr/resource/modelDockerVolume/
  serverDir: /home/satellite/
  workDir: /usr/local/coding/

modelServer:
  #  address: http://127.0.0.1:5001
#  address: http://20.1.182.105:5000
  address: http://model-server:5000
  apis:
    status: /v0/task/status
    result: /v0/task/result
    cancel: /v0/task/cancel
    merge: /v0/tif/merge_v2
    spectrum: /v0/tif/get_spectral_profile
    noCloud: /v0/tif/calc_no_cloud
    noCloud_complex: /v0/tif/calc_no_cloud_complex
    rasterPoint: /v0/tif/calc_raster_point
    rasterLine: /v0/tif/calc_raster_line
    ndvi: /v0/tif/calc_NDVI
    createLowLevelMosaic: /v0/mosaic/create_low_level_mosaic
  interval:
    status: 2

srmodelServer:
  address: http://nrspeclib.sasclouds.com:33445
  apis:
    status: /v0/task/status
    result: /v0/task/result
    SR: /v0/model/superresolution
  interval:
    status: 2

tiler:
  end-point: http://223.2.34.8:31800
#  end-point: http://20.1.37.145:8000
satelliteConfig:
  path: /usr/resource/band_config.json
